receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'k6'
          static_configs:
            - targets: ['localhost:9464']

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging]
